insert  into  CURRENCY_EXCHANGE  (id, CURRENCY_RATE  ,ENVIRONMENT  ,CURRENCY_FROM  ,CURRENCY_TO )
values (10001, 15 , '' , 'USD' , 'TR');

insert  into  CURRENCY_EXCHANGE  (id, CURRENCY_RATE  ,ENVIRONMENT  ,CURRENCY_FROM  ,CURRENCY_TO )
values (10002, 20 , '' , 'EUR' , 'TR');

insert  into  CURRENCY_EXCHANGE  (id, CURRENCY_RATE  ,ENVIRONMENT  ,CURRENCY_FROM  ,CURRENCY_TO )
values (10003, 13 , '' , 'CAD' , 'TR')